### ISSUE TITLE
What type of corruptions to chose from from CIFAR 10c for OOD Detection?

### ISSUE THREAD

**Issue by bezirganyan** [davidmcjung/multiview_uncertainty_estimation#1]
Dear authors, 

I am trying to prepare the data for OOD detection to reproduce the results and compare with other methods. In the paper it is stated that: "The first three corruption types were selected as three multi-view inputs with severity levels of 1, 3, and 5 respectively in order to have variety of noise levels." In CIFAR-10C dataset that I downloaded, my file manager shows the files: `brightness, contrast, defocus_blur, elastic_transform, fog, frost, gaussian_blur, gaussian_noise, glass_blur, impulse_noise, jpeg_compression, labels, motion_blur, pixelate, saturate, shot_noise, snow, spatter, speckle_noise, zoom_blur`, sorted in alphabetical order. Can you please confirm that " the first three corruption types" refer to  `brightness, contrast, defocus_blur`? 

Thanks a lot in advance

**Comment by davidmcjung** [comment]
The three corruptions were taken based on the order originally set from the dataset [(Link)](https://github.com/hendrycks/robustness), which are 'gaussian_noise', 'shot_noise', and 'impulse_noise'.

**Comment by bezirganyan** [comment]
Dear @davidmcjung thanks a lot for the answer. I will close the issue now
