### ISSUE TITLE
How to get preprocessed datasets in mat format ? 

### ISSUE THREAD

**Issue by un0o7** [davidmcjung/multiview_uncertainty_estimation#2]
``
dataset = sio.loadmat(os.path.join(datadir, '2view-caltech101-8677sample.mat'))
``

I don't see any preprocessing methods in your code. Can you provide extra links for these datasets or preprocessing code ?

**Comment by davidmcjung** [comment]
Hi,
The datasets were preprocessed by the authors of [TMC](https://github.com/hanmenghan/TMC/tree/main). Please contact them if you need the datasets as we do not own these.
